namespace: flagger-system
resources:
  - namespace.yaml
bases:
  - github.com/weaveworks/flagger/kustomize/base/flagger
  - github.com/weaveworks/flagger/kustomize/base/prometheus
patchesStrategicMerge:
  - flagger-patch.yaml

images:
  - name: weaveworks/flagger      
    newName: harbor.gcpslab.xyz/library/weaveworks/flagger:1.1.0
    newTag: 1.1.0       
  - name: weaveworks/flagger
    newName: harbor.gcpslab.xyz/library/weaveworks/flagger
    newTag: 2.19.0      
